# Generated by Django 3.0.7 on 2020-06-16 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of business', max_length=25)),
                ('business_abbreviation', models.CharField(help_text='Business name abbreviation', max_length=5)),
                ('company_address', models.CharField(help_text='Address of business', max_length=50)),
                ('country', django_countries.fields.CountryField(default='KE', max_length=2)),
                ('annual_sales_revenue', models.IntegerField(choices=[(1, 'Below KeS 50,000'), (2, 'KeS 50,000 - KeS 150,000'), (3, 'KeS 150,000 - KeS 300,000'), (4, 'KeS 300,000 - KeS 500, 000'), (5, 'Above KeS 500,000')])),
                ('entity', models.CharField(choices=[('R', 'Retailer'), ('S', 'Supplier')], max_length=1)),
                ('accounting_software', models.CharField(choices=[('QB', 'Quickbooks'), ('EX', 'Excel SpreadSheets')], max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
