# Generated by Django 3.0.7 on 2020-06-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('O', 'Orders,'), ('OP', 'Order payments'), ('B', 'Bills'), ('BP', 'Bills Payment)')], max_length=2)),
                ('transaction_id', models.IntegerField()),
                ('transaction_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Completed'), (5, 'Open'), (6, 'Closed')])),
                ('transaction_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('customer_or_supplier', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit_amount', models.FloatField()),
                ('total_transaction', models.FloatField()),
                ('amount', models.FloatField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='businesses.Business')),
            ],
        ),
    ]
