# Generated by Django 3.0.7 on 2020-06-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='total_transaction_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_transaction',
        ),
    ]
