# Generated by Django 3.0.7 on 2020-06-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200616_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Open', 'Open'), ('Closed', 'Closed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Orders', 'Orders'), ('Order payment', 'Order payments'), ('Bill', 'Bills'), ('Bills Payment', 'Bills Payment)')], max_length=15),
        ),
    ]
