# Generated by Django 3.0.7 on 2020-06-17 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_auto_20200617_2343'),
        ('transactions', '0004_auto_20200616_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='businesses.Business'),
        ),
    ]
